export const COUNTY_TO_REGION: Record<string, string> = {
  "london": "London",
  "greater london": "London",
  "city of london": "London",
  "surrey": "South East",
  "kent": "South East",
  "east sussex": "South East",
  "west sussex": "South East",
  "hampshire": "South East",
  "berkshire": "South East",
  "buckinghamshire": "South East",
  "oxfordshire": "South East",
  "isle of wight": "South East",
  "brighton and hove": "South East",
  "southampton": "South East",
  "portsmouth": "South East",
  "reading": "South East",
  "slough": "South East",
  "bracknell forest": "South East",
  "windsor and maidenhead": "South East",
  "wokingham": "South East",
  "medway": "South East",
  "milton keynes": "South East",
  "dorset": "South West",
  "somerset": "South West",
  "devon": "South West",
  "cornwall": "South West",
  "wiltshire": "South West",
  "gloucestershire": "South West",
  "bristol": "South West",
  "bath and north east somerset": "South West",
  "north somerset": "South West",
  "south gloucestershire": "South West",
  "swindon": "South West",
  "bournemouth": "South West",
  "poole": "South West",
  "bournemouth, christchurch and poole": "South West",
  "torbay": "South West",
  "plymouth": "South West",
  "essex": "East of England",
  "hertfordshire": "East of England",
  "bedfordshire": "East of England",
  "cambridgeshire": "East of England",
  "norfolk": "East of England",
  "suffolk": "East of England",
  "peterborough": "East of England",
  "luton": "East of England",
  "southend-on-sea": "East of England",
  "thurrock": "East of England",
  "central bedfordshire": "East of England",
  "bedford": "East of England",
  "leicestershire": "East Midlands",
  "lincolnshire": "East Midlands",
  "derbyshire": "East Midlands",
  "nottinghamshire": "East Midlands",
  "northamptonshire": "East Midlands",
  "rutland": "East Midlands",
  "leicester": "East Midlands",
  "nottingham": "East Midlands",
  "derby": "East Midlands",
  "warwickshire": "West Midlands",
  "staffordshire": "West Midlands",
  "shropshire": "West Midlands",
  "herefordshire": "West Midlands",
  "worcestershire": "West Midlands",
  "west midlands": "West Midlands",
  "coventry": "West Midlands",
  "birmingham": "West Midlands",
  "wolverhampton": "West Midlands",
  "stoke-on-trent": "West Midlands",
  "telford and wrekin": "West Midlands",
  "north yorkshire": "Yorkshire and the Humber",
  "south yorkshire": "Yorkshire and the Humber",
  "west yorkshire": "Yorkshire and the Humber",
  "east yorkshire": "Yorkshire and the Humber",
  "east riding of yorkshire": "Yorkshire and the Humber",
  "yorkshire": "Yorkshire and the Humber",
  "sheffield": "Yorkshire and the Humber",
  "leeds": "Yorkshire and the Humber",
  "bradford": "Yorkshire and the Humber",
  "hull": "Yorkshire and the Humber",
  "kingston upon hull": "Yorkshire and the Humber",
  "york": "Yorkshire and the Humber",
  "north lincolnshire": "Yorkshire and the Humber",
  "north east lincolnshire": "Yorkshire and the Humber",
  "calderdale": "Yorkshire and the Humber",
  "kirklees": "Yorkshire and the Humber",
  "wakefield": "Yorkshire and the Humber",
  "doncaster": "Yorkshire and the Humber",
  "rotherham": "Yorkshire and the Humber",
  "barnsley": "Yorkshire and the Humber",
  "lancashire": "North West",
  "cheshire": "North West",
  "cumbria": "North West",
  "greater manchester": "North West",
  "merseyside": "North West",
  "manchester": "North West",
  "liverpool": "North West",
  "salford": "North West",
  "cheshire east": "North West",
  "cheshire west and chester": "North West",
  "warrington": "North West",
  "halton": "North West",
  "knowsley": "North West",
  "sefton": "North West",
  "st helens": "North West",
  "wirral": "North West",
  "bolton": "North West",
  "bury": "North West",
  "oldham": "North West",
  "rochdale": "North West",
  "stockport": "North West",
  "tameside": "North West",
  "trafford": "North West",
  "wigan": "North West",
  "blackburn with darwen": "North West",
  "blackpool": "North West",
  "county durham": "North East",
  "northumberland": "North East",
  "tyne and wear": "North East",
  "durham": "North East",
  "newcastle upon tyne": "North East",
  "newcastle": "North East",
  "sunderland": "North East",
  "gateshead": "North East",
  "south tyneside": "North East",
  "north tyneside": "North East",
  "middlesbrough": "North East",
  "stockton-on-tees": "North East",
  "hartlepool": "North East",
  "darlington": "North East",
  "redcar and cleveland": "North East",
  "scotland": "Scotland",
  "edinburgh": "Scotland",
  "glasgow": "Scotland",
  "highland": "Scotland",
  "aberdeenshire": "Scotland",
  "aberdeen": "Scotland",
  "fife": "Scotland",
  "perth and kinross": "Scotland",
  "stirling": "Scotland",
  "dundee": "Scotland",
  "south lanarkshire": "Scotland",
  "north lanarkshire": "Scotland",
  "east lothian": "Scotland",
  "west lothian": "Scotland",
  "midlothian": "Scotland",
  "angus": "Scotland",
  "renfrewshire": "Scotland",
  "east renfrewshire": "Scotland",
  "inverclyde": "Scotland",
  "east ayrshire": "Scotland",
  "north ayrshire": "Scotland",
  "south ayrshire": "Scotland",
  "argyll and bute": "Scotland",
  "falkirk": "Scotland",
  "clackmannanshire": "Scotland",
  "dumfries and galloway": "Scotland",
  "scottish borders": "Scotland",
  "orkney": "Scotland",
  "shetland": "Scotland",
  "western isles": "Scotland",
  "moray": "Scotland",
  "east dunbartonshire": "Scotland",
  "west dunbartonshire": "Scotland",
  "wales": "Wales",
  "cardiff": "Wales",
  "swansea": "Wales",
  "newport": "Wales",
  "caerphilly": "Wales",
  "rhondda cynon taf": "Wales",
  "neath port talbot": "Wales",
  "bridgend": "Wales",
  "vale of glamorgan": "Wales",
  "merthyr tydfil": "Wales",
  "flintshire": "Wales",
  "wrexham": "Wales",
  "denbighshire": "Wales",
  "conwy": "Wales",
  "gwynedd": "Wales",
  "isle of anglesey": "Wales",
  "ceredigion": "Wales",
  "pembrokeshire": "Wales",
  "carmarthenshire": "Wales",
  "powys": "Wales",
  "blaenau gwent": "Wales",
  "torfaen": "Wales",
  "monmouthshire": "Wales",
  "northern ireland": "Northern Ireland",
  "belfast": "Northern Ireland",
  "antrim": "Northern Ireland",
  "armagh": "Northern Ireland",
  "down": "Northern Ireland",
  "fermanagh": "Northern Ireland",
  "londonderry": "Northern Ireland",
  "derry": "Northern Ireland",
  "tyrone": "Northern Ireland",
  "antrim and newtownabbey": "Northern Ireland",
  "ards and north down": "Northern Ireland",
  "belfast city": "Northern Ireland",
  "causeway coast and glens": "Northern Ireland",
  "derry city and strabane": "Northern Ireland",
  "fermanagh and omagh": "Northern Ireland",
  "lisburn and castlereagh": "Northern Ireland",
  "mid and east antrim": "Northern Ireland",
  "mid ulster": "Northern Ireland",
  "newry, mourne and down": "Northern Ireland",
};

export function countyToRegion(county: string | null | undefined): string | null {
  if (!county) return null;
  return COUNTY_TO_REGION[county.toLowerCase().trim()] ?? null;
}
