import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import storageRouter from "./storage";
import profileRouter from "./profiles";
import consentRouter from "./consent";
import documentsRouter from "./documents";
import eligibilityRouter from "./eligibility";
import rulesetsRouter from "./rulesets";
import rolesRouter from "./roles";
import sponsorshipRouter from "./sponsorship";
import remediationRouter from "./remediation";
import aiRouter from "./ai";
import reviewRouter from "./review";
import adminAuditRouter from "./adminAudit";
import applicationsRouter from "./applications";
import employerRouter from "./employer";
import smartApplyRouter from "./smartApply";
import interviewPrepRouter from "./interviewPrep";
import adminUsersRouter from "./adminUsers";
import sponsorLicencesRouter from "./sponsorLicences";
import coverLetterRouter from "./coverLetter";
import progressReportRouter from "./progressReport";
import speculativeApplicationsRouter from "./speculativeApplications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(storageRouter);
router.use(profileRouter);
router.use(consentRouter);
router.use(documentsRouter);
router.use(eligibilityRouter);
router.use(rulesetsRouter);
router.use(rolesRouter);
router.use(sponsorshipRouter);
router.use(remediationRouter);
router.use(aiRouter);
router.use(reviewRouter);
router.use(adminAuditRouter);
router.use(applicationsRouter);
router.use(employerRouter);
router.use(smartApplyRouter);
router.use(interviewPrepRouter);
router.use(adminUsersRouter);
router.use(sponsorLicencesRouter);
router.use(coverLetterRouter);
router.use(progressReportRouter);
router.use(speculativeApplicationsRouter);

export default router;
