import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import storageRouter from "./storage";
import profileRouter from "./profiles";
import consentRouter from "./consent";
import documentsRouter from "./documents";
import eligibilityRouter from "./eligibility";
import rulesetsRouter from "./rulesets";
import rolesRouter from "./roles";
import sponsorshipRouter from "./sponsorship";
import remediationRouter from "./remediation";
import aiRouter from "./ai";
import reviewRouter from "./review";
import adminAuditRouter from "./adminAudit";
import applicationsRouter from "./applications";
import employerRouter from "./employer";
import smartApplyRouter from "./smartApply";
import interviewPrepRouter from "./interviewPrep";
import adminUsersRouter from "./adminUsers";
import sponsorLicencesRouter from "./sponsorLicences";
import coverLetterRouter from "./coverLetter";
import progressReportRouter from "./progressReport";
import analyticsReportRouter from "./analyticsReport";
import speculativeApplicationsRouter from "./speculativeApplications";
import superAdminRouter from "./superAdmin";
import journeyRouter from "./journey";
import nudgeRouter from "./nudge";
import recommendationLettersRouter from "./recommendationLetters";
import identityRouter from "./identity";
import careerProfilesRouter from "./careerProfiles";
import internalSyncRouter from "./internalSync";
import inboundEmailRouter from "./inboundEmail";
import vacancyFavoritesRouter from "./vacancyFavorites";
import leadsRouter from "./leads";
import vacancyLinkCheckRouter from "./vacancyLinkCheck";
import cvEnhancementRouter from "./cvEnhancement";
import readinessClaimsRouter from "./readinessClaims";
import internalVacancyJobsRouter from "./internalVacancyJobs";
import marketerCalendarRouter from "./marketerCalendar";
import sponsorWebsiteImportRouter from "./sponsorWebsiteImport";
import internalCompanySiteWorkflowRouter from "./internalCompanySiteWorkflow";
import checkoutRouter from "./checkout";
import supportRouter from "./support";
import readinessRouter from "./readiness";
import feedbackRouter from "./feedback";
import descriptionFeedbackRouter from "./descriptionFeedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(storageRouter);
router.use(profileRouter);
router.use(consentRouter);
router.use(documentsRouter);
router.use(eligibilityRouter);
router.use(rulesetsRouter);
router.use(rolesRouter);
router.use(sponsorshipRouter);
router.use(remediationRouter);
router.use(aiRouter);
router.use(reviewRouter);
router.use(adminAuditRouter);
router.use(applicationsRouter);
router.use(employerRouter);
router.use(smartApplyRouter);
router.use(interviewPrepRouter);
router.use(adminUsersRouter);
router.use(sponsorLicencesRouter);
router.use(coverLetterRouter);
router.use(progressReportRouter);
router.use(analyticsReportRouter);
router.use(speculativeApplicationsRouter);
router.use(superAdminRouter);
router.use(journeyRouter);
router.use(nudgeRouter);
router.use(recommendationLettersRouter);
router.use(identityRouter);
router.use(careerProfilesRouter);
router.use(internalSyncRouter);
router.use(inboundEmailRouter);
router.use(vacancyFavoritesRouter);
router.use(leadsRouter);
router.use(vacancyLinkCheckRouter);
router.use(cvEnhancementRouter);
router.use(readinessClaimsRouter);
router.use(internalVacancyJobsRouter);
router.use(marketerCalendarRouter);
router.use(sponsorWebsiteImportRouter);
router.use(internalCompanySiteWorkflowRouter);
router.use(checkoutRouter);
router.use(supportRouter);
router.use(readinessRouter);
router.use(feedbackRouter);
router.use(descriptionFeedbackRouter);

export default router;
